#!/usr/bin/env bash
set -euo pipefail

# AgentKit vendor_rules.sh (Core)
# Purpose:
# - Maintain .agentkit/rules/NOTICE as a machine-updated summary of vendored rule sources.
# - Maintain .agentkit/rules/UPSTREAM_LICENSES/ as the place to store upstream licenses.
#
# This Core script does NOT fetch upstream repos by itself (no network assumptions).
# Instead, it:
# - reads a local manifest file if present,
# - writes/updates NOTICE deterministically.
#
# Later (when we vendor specific upstream rule sets), we can extend this script to:
# - copy files into rules/common or rules/stacks/<stack>,
# - copy upstream LICENSE texts into UPSTREAM_LICENSES/,
# while still keeping NOTICE auto-updated.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RULES_DIR="$ROOT_DIR/.agentkit/rules"
NOTICE_FILE="$RULES_DIR/NOTICE"
LICENSE_DIR="$RULES_DIR/UPSTREAM_LICENSES"
MANIFEST_FILE="$RULES_DIR/VENDORED_SOURCES.txt"

mkdir -p "$LICENSE_DIR"

timestamp_utc() {
  # ISO-8601 UTC
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

write_notice_header() {
  cat > "$NOTICE_FILE" <<EOF
AgentKit NOTICE (auto-generated)

This NOTICE file is updated by:
  .agentkit/scripts/vendor_rules.sh

Do not edit this file manually unless you know what you're doing.

Last updated (UTC): $(timestamp_utc)

EOF
}

append_notice_body_from_manifest() {
  if [[ ! -f "$MANIFEST_FILE" ]]; then
    cat >> "$NOTICE_FILE" <<EOF
No vendored sources manifest found.

To track vendored rule sources, create:
  .agentkit/rules/VENDORED_SOURCES.txt

Format (one source per block):
  Name: <source name>
  URL: <source url>
  License: <license id/name>
  VendoredPaths: <comma-separated paths inside this repo>
  LicenseFile: <path under .agentkit/rules/UPSTREAM_LICENSES/>

Example:
  Name: everything-claude-code
  URL: https://github.com/affaan-m/everything-claude-code
  License: MIT
  VendoredPaths: .agentkit/rules/common/*,.agentkit/rules/stacks/python/*
  LicenseFile: .agentkit/rules/UPSTREAM_LICENSES/everything-claude-code_MIT.txt

EOF
    return 0
  fi

  cat >> "$NOTICE_FILE" <<EOF
Vendored sources (from VENDORED_SOURCES.txt):

EOF

  # Copy manifest verbatim but with stable formatting:
  # - strip trailing spaces
  # - ensure blank line between blocks
  awk '{ sub(/[ \t\r]+$/, "", $0); print $0 }' "$MANIFEST_FILE" >> "$NOTICE_FILE"
  echo "" >> "$NOTICE_FILE"
}

main() {
  write_notice_header
  append_notice_body_from_manifest

  echo "✅ Updated NOTICE: $NOTICE_FILE"
  echo "ℹ️  Licenses directory: $LICENSE_DIR"
  if [[ -f "$MANIFEST_FILE" ]]; then
    echo "ℹ️  Manifest found: $MANIFEST_FILE"
  else
    echo "ℹ️  Manifest not found (created NOTICE with guidance)."
  fi
}

main "$@"
